# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDJjMjRiMGI2YTEzNWIwZGYyNjMyZjQzOGQwMzJlZmE1MzQxZGY1NWU3OWM3NWJkNzk2MWJlMmU5MDFmOTU1NzNhZTM3MTQ5OWZhOTU3ZDRjZGY3ODBkMjk4ZDhlM2E5ZjNjNTQ3N2FhNGEzNWUwZDdiNjYzNzgxYjU1OTZhNWE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
